kind: wasmer.io/App.v0
name: plumber-portal-enoew
package: enoew/plumber-portal
```[[1](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQE2-AKIbUpanEkJh8xCZwcv_wPXxYWP649NoiBNPuD0m9vX8sx1jZ4yMFdOFQYUx4-k6yd4CXp_1xlSlCgRv_s4xnUArcg8bIj7N_aTvPxobzlnXLGVjRdvqZu6yeULUDrVAubqMA%3D%3D)]
